# Generated by Django 2.0.6 on 2018-10-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=120)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, choices=[(1, 'Starting'), (1, 'In Progress'), (1, 'Finished')], null=True)),
            ],
        ),
    ]
