# Generated by Django 2.0.6 on 2018-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementlog',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Starting'), (2, 'In Progress'), (3, 'Finished')], null=True),
        ),
    ]
